### PR TITLE
Introducing the Aggeregate MP Estimation Logic

### PR DESCRIPTION
**Pull request by mart1n-xyz**
## Description

The expected number of MPs generated in an epoch is estimated when it is started. This is used to distribute rewards. If users are not able to mint all. expected MPs due to the limit, the estimated is reduced by this amount and subsequent claimants are served with a more accurate estimate. 

## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [ ] Added natspec comments?
- [ ] Ran `forge snapshot`?
- [ ] Ran `pnpm lint`?
- [ ] Ran `forge test`?

### CODE REVIEW

**Review by 0x-r4bbit — CHANGES_REQUESTED** [review]
@mart1n-xyz `iEpoch` does indeed not exist there. You need to know which user epoch you're operating on.

**Comment by 0x-r4bbit** [comment]
@mart1n-xyz I believe we can close this PR. There has been some changes in this part in #47 and AFAIK @3esmit is working on updating the MP estimation logic right now.

Can you please give me a ping here if this is okay to be closed?

**Comment by mart1n-xyz** [comment]
Yes, feel free to close. Me and @3esmit discussed the points in question and Ricardo's next iteration should address this.

**Comment by 0x-r4bbit** [comment]
Thank you for the update!

**Pull request closed without merging**
