### PR TITLE
chore: update package.json and README.md

### LINKED ISSUE #131: Readme and package.json need maintance
These files are all defaults from the template, which looks bad.

### PR DESCRIPTION
**Pull request by 3esmit**
## Description

This should make project more good looking.

Updates package.json with:
- new gas-report: uses stderr to allow work on non interactive terminals
- faster adorno: avoid testing contracts 2 times
- updates author: Add IFT data
- add engine: set engine to be at least node 18
- add repository
- add bugs

Updates README.md

Add actual information on this project, removing the template readme.

Fixes #131 

## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [ ] Added natspec comments?
- [ ] Ran `forge snapshot`?
- [ ] Ran `pnpm gas-report`?
- [ ] Ran `pnpm lint`?
- [ ] Ran `forge test`?
- [ ] Ran `pnpm verify`?

### CODE REVIEW

**Comment by 3esmit** [comment]
I'll add more text to features, just noticed I missed an important features which is migration system. I'll review this tomorrow morning. If you have any other ideas on what to put on read me let me know

**Comment by 0x-r4bbit** [comment]
This PR should not include any changes to the gas reports.

**Review by 0x-r4bbit — APPROVED** [review]

**Comment by 3esmit** [comment]
This is happening because of #133, once we fix that this should stop happening. My commits automatically include gas reports if they change. Do you prefer fixing #133 first than coming to this issue?

**Comment by 0x-r4bbit** [comment]
I don't think changes to the readme and package.json should be blocked by the gas-reports changing due to fuzzing.
So let's merge this.

Thank you for doing this!

**Comment by 3esmit** [comment]
I'll just add something on readme...

**Pull request merged**
